### ISSUE TITLE
Error when running requirements.txt install (cannot build wheels for pillow)

### ISSUE THREAD

**Issue by sangaleandy** [justdjango/django-ecommerce#120]
(env) C:\Users\Administrator\Downloads\User\Web design\1\django-ecommerce>pip install -r requirements.txt
Collecting autopep8==1.4.4 (from -r requirements.txt (line 1))
  Using cached autopep8-1.4.4-py2.py3-none-any.whl
Collecting certifi==2019.3.9 (from -r requirements.txt (line 2))
  Using cached certifi-2019.3.9-py2.py3-none-any.whl (158 kB)
Collecting chardet==3.0.4 (from -r requirements.txt (line 3))
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting defusedxml==0.6.0 (from -r requirements.txt (line 4))
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting Django==2.2.14 (from -r requirements.txt (line 5))
  Using cached Django-2.2.14-py3-none-any.whl (7.5 MB)
Collecting django-allauth==0.39.1 (from -r requirements.txt (line 6))
  Using cached django_allauth-0.39.1-py3-none-any.whl
Collecting django-countries==5.3.3 (from -r requirements.txt (line 7))
  Using cached django_countries-5.3.3-py2.py3-none-any.whl (706 kB)
Collecting django-crispy-forms==1.7.2 (from -r requirements.txt (line 8))
  Using cached django_crispy_forms-1.7.2-py2.py3-none-any.whl (105 kB)
Collecting django-debug-toolbar==1.10.1 (from -r requirements.txt (line 9))
  Using cached django_debug_toolbar-1.10.1-py2.py3-none-any.whl (207 kB)
Collecting idna==2.8 (from -r requirements.txt (line 10))
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting oauthlib==3.0.1 (from -r requirements.txt (line 11))
  Using cached oauthlib-3.0.1-py2.py3-none-any.whl (142 kB)
Collecting pep8==1.7.1 (from -r requirements.txt (line 12))
  Using cached pep8-1.7.1-py2.py3-none-any.whl (41 kB)
Collecting Pillow==6.2.2 (from -r requirements.txt (line 13))
  Using cached Pillow-6.2.2.tar.gz (37.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycodestyle==2.5.0 (from -r requirements.txt (line 14))
  Using cached pycodestyle-2.5.0-py2.py3-none-any.whl (51 kB)
Collecting python-decouple==3.1 (from -r requirements.txt (line 15))
  Using cached python_decouple-3.1-py3-none-any.whl
Collecting python3-openid==3.1.0 (from -r requirements.txt (line 16))
  Using cached python3_openid-3.1.0-py3-none-any.whl (130 kB)
Collecting pytz==2018.5 (from -r requirements.txt (line 17))
  Using cached pytz-2018.5-py2.py3-none-any.whl (510 kB)
Collecting requests==2.21.0 (from -r requirements.txt (line 18))
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting requests-oauthlib==1.2.0 (from -r requirements.txt (line 19))
  Using cached requests_oauthlib-1.2.0-py2.py3-none-any.whl (22 kB)
Collecting sqlparse==0.2.4 (from -r requirements.txt (line 20))
  Using cached sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
Collecting stripe==2.27.0 (from -r requirements.txt (line 21))
  Using cached stripe-2.27.0-py2.py3-none-any.whl (196 kB)
Collecting urllib3==1.24.2 (from -r requirements.txt (line 22))
  Using cached urllib3-1.24.2-py2.py3-none-any.whl (131 kB)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [197 lines of output]
      <string>:28: RuntimeWarning: Pillow does not yet support Python 3.12 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-312\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.codecov.yml'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'azure-pipelines.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.azure-pipelines'
      no previously-included directories found matching '.travis'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 852, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 687, in build_extensions
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\Administrator\Downloads\User\Web design\1\django-ecommerce\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\Downloads\User\Web design\1\django-ecommerce\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\Downloads\User\Web design\1\django-ecommerce\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-xj34lrz6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 903, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

**Comment by darkb0ts** [comment]
Pillow has system-level dependencies that need to be installed before installing Pillow itself. On Debian-based systems, you can install them using:        `sudo apt-get install libjpeg-dev zlib1g-dev libtiff-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk`

**Comment by sangaleandy** [comment]
Okay thanks, let me try it out

**Comment by Kipng3n0** [comment]
Hey, did you managed to do it?

**Comment by sangaleandy** [comment]
Yes, it is working well finally, thanks

**Comment by Kipng3n0** [comment]
can you guide me how you went about it?

**Comment by Kipng3n0** [comment]
Share your number we talk on whatsapp

**Comment by sangaleandy** [comment]
+254702977498

**Comment by amiii123malviya** [comment]
Hello,

Is this issue still active?
I would like to work on this.

Best Regards.

**Comment by sangaleandy** [comment]
No, it worked fine finally

**Comment by amiii123malviya** [comment]
Okay, thankyou so much for your time .

Regards

**Comment by sangaleandy** [comment]
You are welcome.

**Comment by helenamcr2004-stack** [comment]
For me
Deleting and copying the repository again and then change the django-allauth to version `django-allauth==0.50.0 ` in the `requirements.txt` solved the problem.
