### ISSUE TITLE
ImportError: cannot import name 'config' from 'decouple'

### ISSUE THREAD

**Issue by salman77713438** [justdjango/django-ecommerce#45]
i got this error when i try to runserver
please help!!!!!!!!!!!!!!
my steps 
1- pip install virtualenv
2- virtualenv env 
3- source env/bin/active 
4- pip install -r requirements.txt
5- python manage.py runserver

`_Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\commands\runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pc\Downloads\django-ecommerce-master\django-ecommerce-master\djecommerce\settings\development.py", line 1, in <module>
    from .base import *
  File "C:\Users\pc\Downloads\django-ecommerce-master\django-ecommerce-master\djecommerce\settings\base.py", line 2, in <module>
    from decouple import config
ImportError: cannot import name 'config' from 'decouple' (C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\base.py", line 336, in run_from_argv
    connections.close_all()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\utils.py", line 219, in close_all
    for alias in self:
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\utils.py", line 213, in __iter__
    return iter(self.databases)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pc\Downloads\django-ecommerce-master\django-ecommerce-master\djecommerce\settings\development.py", line 1, in <module>
    from .base import *
  File "C:\Users\pc\Downloads\django-ecommerce-master\django-ecommerce-master\djecommerce\settings\base.py", line 2, in <module>
    from decouple import config
ImportError: cannot import name 'config' from 'decouple' (C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple\__init__.py)_`

**Comment by sakibsadmanshajib** [comment]
I think you might have misconfigured your virtual environment or some packages aren't being installed properly. I ran the program myself. It sorta worked. Let me know if I can help.

**Comment by zeeshan606115** [comment]
The same error is showing to me also

**Comment by zeeshan606115** [comment]
> I think you might have misconfigured your virtual environment or some packages aren't being installed properly. I ran the program myself. It sorta worked. Let me know if I can help.

Bro can u please show me the python packages which you have installed.

**Comment by AbdalhalemHosni-eng** [comment]
i got this erro also

**Comment by AbdalhalemHosni-eng** [comment]
i got it pepole
first activate ther virtual enviroment 
run this => pip uninstall decouple
and run this => from .conf import con

this soulution worked with me

**Comment by mrvayd** [comment]
![image](https://user-images.githubusercontent.com/64084172/115704109-95db7780-a388-11eb-91b2-d4b65c067c75.png)

**Comment by mrvayd** [comment]
Help it is showing this error

**Comment by vincent50** [comment]
Hi!
you need install python-decouple not decouple

if you have installed decouple first uninstall with:
`pip uninstall decouple`

then install python-decouple:
`pip install python-decouple`

or only replace the requirements file with:
python-decouple==3.4

**Comment by rkovilpillai** [comment]
Thanks @vincent50 , Your solution helpmed to fix the error !!

**Comment by JanakXD** [comment]
> Hi!
> you need install python-decouple not decouple
> 
> if you have installed decouple first uninstall with:
> `pip uninstall decouple`
> 
> then install python-decouple:
> `pip install python-decouple`
> 
> or only replace the requirements file with:
> python-decouple==3.4

thanks @vincent50 this helped me too

**Comment by Parl-Shedge** [comment]
you have to install :  
step 1:
> pip install python-decouple

if you have install 

> pip install decouple  (uninstall it first)
then follow step 1 :
