### ISSUE TITLE
ModuleNotFoundError: No module named 'decouple'

### ISSUE THREAD

**Issue by kirti-yelavikar** [justdjango/django-ecommerce#69]
When I tried to run server with command:

>python manage.py runserver

a big error log comes this isthe last part of that error log:

    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module      
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

H:\study material\Web development\React\ecom\django-ecommerce>python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module      
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "H:\study material\Web development\React\ecom\django-ecommerce\djecommerce\settings\development.py", line 1, in <module>
    from .base import *
  File "H:\study material\Web development\React\ecom\django-ecommerce\djecommerce\settings\base.py", line 2, in <module>  
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\study material\Web development\React\ecom\django-ecommerce\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 
401, in execute_from_command_line
    utility.execute()
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 
395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 343, in run_from_argv
    connections.close_all()
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 232, in close_all
    for alias in self:
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 226, in __iter__
    return iter(self.databases)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\kirti\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module      
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "H:\study material\Web development\React\ecom\django-ecommerce\djecommerce\settings\development.py", line 1, in <module>
    from .base import *
  File "H:\study material\Web development\React\ecom\django-ecommerce\djecommerce\settings\base.py", line 2, in <module>  
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

**Comment by shreyashsrivastava** [comment]
Did you run this first `pip install -r requirements.txt` ?

**Comment by thethinkingmonks** [comment]
you need to create your virtual env and install the packages
