### ISSUE TITLE
ModuleNotFoundError: allauth

### ISSUE THREAD

**Issue by Nextaar** [justdjango/django-ecommerce#99]
(nex) PS C:\Users\nexta\Documents\python project\My e-commerce website> python manage.py rename nextecommerce
Traceback (most recent call last):
  File "C:\Users\nexta\Documents\python project\My e-commerce website\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\nexta\Documents\python project\My e-commerce website\nex\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\nexta\Documents\python project\My e-commerce website\nex\lib\site-packages\django\core\management\__init__.py", line 420, in execute
    django.setup()
  File "C:\Users\nexta\Documents\python project\My e-commerce website\nex\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\nexta\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth'(nex) 
PS C:\Users\nexta\Documents\python project\My e-commerce website>

How to fix this new to Projects!

**Comment by MohammadSamandar** [comment]
You can wrie it:

**Comment by MohammadSamandar** [comment]
You can writ it:
python -m pip install django-allauth
